### ISSUE TITLE
Installation docs out of step with Tailwind 4.0?

### ISSUE THREAD

**Issue by rmx90210** [radix-vue/shadcn-vue#1036]
Hello, and thank you for this awesome project!

I'm trying to use shadcn-vue but I'm running into some issues. Here's what I've tried so far:

- Create new Vue project with `pnpm create vue@latest`
- Follow Tailwind 4.0 installation [docs](https://tailwindcss.com/docs/installation/using-vite) (note: using the Vite plugin method, not PostCSS)
- Follow shadcn-vue installation [docs](https://www.shadcn-vue.com/docs/installation/vite.html)

It's confusing me a bit that the shadcn-vue docs have me install Tailwind, but using different steps than the official Tailwind docs. For example, the Tailwind docs don't mention `autoprefixer`, but the shadcn-vue docs do. Also shadcn-vue says to install Tailwind as a dev dependency, while the Tailwind docs do not. I'm not sure which method I should be using to install Tailwind.

I would be happy to help with a PR to update the documentation to make it a bit more in sync with Tailwind, and friendlier for beginners!

**Comment by whiteair** [comment]
how did you solve this problem?
i seem to be getting a beginners error.
error when starting dev server:

Error: It looks like you're trying to use `tailwindcss` directly as a PostCSS plugin. The PostCSS plugin has moved to a separate package, so to continue using Tailwind CSS with PostCSS you'll need to install `@tailwindcss/postcss` and update your PostCSS configuration.

**Comment by rmx90210** [comment]
@whiteair I wish I could help but I haven't solved it yet -- sorry!

**Comment by kakauandme** [comment]
Looks like Tailwind 4 is not supported yet.

**Comment by mhaib** [comment]
@whiteair Tailwind 4 is not yet supported, so the dependency needs to be downgraded to Tailwind 3 with `tailwindcss@3`

**Comment by pushpan999** [comment]
Install vue with vite, and shadcn-vue as in documentation.
configure vite.config.ts

import { fileURLToPath, URL } from 'node:url'
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import tailwindcss from '@tailwindcss/vite'

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    tailwindcss(),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  }
})

You don't need tailwind.config.js in tailwindcss 4, and there are major changes in tailwind4 color variables...
Update your css to something like below to make shadcn pick the correct colors

@import "tailwindcss";
@theme {
  /* Base colors */
  --color-background: oklch(1 0 0);
  --color-foreground: oklch(0.279 0.02 262.86);
  
  /* Muted colors */
  --color-muted: oklch(0.96 0.015 240.01);
  --color-muted-foreground: oklch(0.48 0.024 262.37);
  
  /* Card colors */
  --color-card: oklch(1 0 0);
  --color-card-foreground: oklch(0.279 0.02 262.86);...

since tailwind4 doesn't come with styles border, you may want to update your css to match shadcn default theme..
@layer utilities {
  .border, .border-b, .border-t, .border-l, .border-r {
    @apply border-gray-300;
   }
}

**Comment by clementmas** [comment]
It looks like someone started to work on a Tailwind v4 PR: https://github.com/unovue/shadcn-vue/pull/1024

**Comment by guhweb** [comment]
I did what @pushpan999 mentioned and got an overwhelming result! Here I'm running tailwindcss@4.0.1 together with shadcn (although it doesn't offer official support yet).

To convert the colors from hsl to oklch format, I used the website https://oklch.com/ and got the following results.

I took into account tailwind.config.js, which would be created in the tailwind@3 format, and I simply rewrote it to the new format accepted directly in style.css.

```css
@theme {
    --color-background: oklch(1 0 0);
    --color-foreground: oklch(0.279 0.02 262.86);

    --color-muted: oklch(0.96 0.015 240.01);
    --color-muted-foreground: oklch(0.48 0.024 262.37);

    --color-card: oklch(1 0 0);
    --color-card-foreground: oklch(0.279 0.02 262.86);

    --color-popover: oklch(0.96 0.015 240.01);
    --color-popover-foreground: oklch(0.48 0.024 262.37);

    --color-border: oklch(92.78 0.0058 264.53);
    --color-input: oklch(0.96 0.015 240.01);

    --color-primary: oklch(21.03% 0.0318 264.65);
    --color-primary-foreground: oklch(98.43% 0.0017 247.84);

    --color-secondary: oklch(96.71% 0.0029 264.54);
    --color-secondary-foreground: oklch(21.03% 0.0318 264.65);

    --color-accent: oklch(96.71% 0.0029 264.54);
    --color-accent-foreground: oklch(21.03% 0.0318 264.65);

    --color-destructive: oklch(63.68% 0.2078 25.33);
    --color-destructive-foreground: oklch(98.43% 0.0017 247.84);

    --color-ring: oklch(87.15% 0.0094 258.34);
}

@variant dark {
    --color-background: oklch(0.279 0.02 262.86);
    --color-foreground: oklch(1 0 0);

    --color-muted: oklch(27.84% 0.0296 256.85);
    --color-muted-foreground: oklch(71.37% 0.0192 261.33);

    --color-popover: oklch(12.94% 0.0273 261.67);
    --color-popover-foreground: oklch(98.43% 0.0017 247.84);

    --color-card: oklch(12.94% 0.0273 261.67);
    --color-card-foreground: oklch(98.43% 0.0017 247.84);

    --color-border: oklch(27.84% 0.0296 256.85);
    --color-input: oklch(27.84% 0.0296 256.85);

    --color-primary: oklch(98.43% 0.0017 247.84);
    --color-primary-foreground: oklch(21.03% 0.0318 264.65);

    --color-secondary: oklch(27.84% 0.0296 256.85);
    --color-secondary-foreground: oklch(98.43% 0.0017 247.84);

    --color-accent: oklch(27.84% 0.0296 256.85);
    --color-accent-foreground: oklch(98.43% 0.0017 247.84);

    --color-destructive: oklch(39.59% 0.1331 25.72);
    --color-destructive-foreground: oklch(98.43% 0.0017 247.84);

    --color-ring: oklch(87.15% 0.0094 258.34);
}

@layer utilities {
    .border, .border-b, .border-t, .border-l, .border-r {
        @apply border-gray-300;
    }
}

```

**Comment by guhweb** [comment]
Regarding keyframes and animations, you should add the following code snippet below within the @theme directive.

Note: From tailwind.config.js, it is not necessary to migrate the border radius, because they already follow the standard.

Remember to add the @plugin directive above the @theme

```shell
npm install -D tailwindcss-animate
```

```css
@plugin "tailwindcss-animate";
```

```css
@keyframes accordion-down {
    from {
        height: 0
    }
    to {
        height: var(--radix-accordion-content-height)
    }
}

@keyframes accordion-up {
    from {
        height: var(--radix-accordion-content-height)
    }
    to {
        height: 0
    }
}

@keyframes collapsible-down {
    from {
        height: 0
    }
    to {
        height: var(--radix-collapsible-content-height)
    }
}

@keyframes collapsible-up {
    from {
        height: var(--radix-collapsible-content-height)
    }
    to {
        height: 0
    }
}

--animate-accordion-down: accordion-down 0.2s ease-out;
--animate-accordion-up: accordion-up 0.2s ease-out;
--animate-collapsible-down: collapsible-down 0.2s ease-in-out;
--animate-collapsible-up: collapsible-up 0.2s ease-in-out;
```
