### ISSUE TITLE
[Bug]: Sidebar not styled

### ISSUE THREAD

**Issue by Soviut** [radix-vue/shadcn-vue#911]
### Reproduction

https://stackblitz.com/edit/hxwcmp?file=src%2FApp.vue

### Describe the bug

The sidebar styles that I see in the docs do not seem to be applying for me. I was able to reproduce this in the example.

I've tried deleting my `components/sidebar` folder and re-adding the component. I've also tried doing a `shadcn-vue init` both with and without CSS variables. Nothing seems to add the styles that exist in the examples.

### System Info

```bash
System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i5-1340P
    Memory: 25.26 GB / 31.06 GB
    Container: Yes
    Shell: 5.2.21 - /bin/bash
  Binaries:
    Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
    npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
  npmPackages:
    @vueuse/core: ^11.2.0 => 11.2.0
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by Whbbit1999** [comment]
Sidebar background？You need add some css variable in yor base css variable file.

**Comment by EthanITA** [comment]
@Soviut 

Sidebar is not styled because it misses classes and variables.

In your main css add the following variables:
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root{
    ....

    --sidebar-background: 0 0% 98%;
    --sidebar-foreground: 240 5.3% 26.1%;
    --sidebar-primary: 240 5.9% 10%;
    --sidebar-primary-foreground: 0 0% 98%;
    --sidebar-accent: 240 4.8% 95.9%;
    --sidebar-accent-foreground: 240 5.9% 10%;
    --sidebar-border: 220 13% 91%;
    --sidebar-ring: 217.2 91.2% 59.8%;
  }
  .dark {
     ...
     
    --sidebar-background: 240 5.9% 10%;
    --sidebar-foreground: 240 4.8% 95.9%;
    --sidebar-primary: 224.3 76.3% 48%;
    --sidebar-primary-foreground: 0 0% 100%;
    --sidebar-accent: 240 3.7% 15.9%;
    --sidebar-accent-foreground: 240 4.8% 95.9%;
    --sidebar-border: 240 3.7% 15.9%;
    --sidebar-ring: 217.2 91.2% 59.8%;
  }
}
```


Then update your tailwind.config and add "sidebar" classes:

```javascript
module.exports = {
  theme: {
    extend: {
      colors: {
        sidebar: {
          background: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
    },
  },
};

```
